apriltag_detector:
  ros__parameters:
    max_hamming_distance: 1
    tag_sizes:
      "0": 0.075
      "1": 0.075
      "2": 0.075 
      "3": 0.024
      "4": 0.024
      "5": 0.024
      "6": 0.024
      "7": 0.024
      "8": 0.024
      "9": 0.024
